import Item from "./models/item.type";

const rawMaterialDefList: {
  [key: string]: Item;
} = {
  wood: {
    name: "Wood",
    description: "A piece of wood.",
    defName: "wood",
    price: 0.3,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    requiredSkill: undefined,
    rarity: "common",
    itemType: "rawMaterial",
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
  },
  rawFish: {
    name: "Raw Fish",
    description: "A raw fish. You can not eat it but you can cook it.",
    defName: "rawFish",
    price: 0.2,
    isCookable: true,
    processedItem: "bakedFish",
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    requiredSkill: undefined,
    rarity: "common",
    itemType: "rawMaterial",
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    hungerRestore: 0,
  },
  stoneOre: {
    name: "Stone Ore",
    description: "A piece of stone ore.",
    defName: "stoneOre",
    price: 0.1,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    requiredSkill: undefined,
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    itemType: "rawMaterial",
    rarity: "common",
  },
  copperOre: {
    name: "Copper Ore",
    description: "A piece of copper ore.",
    defName: "copperOre",
    price: 0.5,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    itemType: "rawMaterial",
    rarity: "common",
    requiredSkill: undefined,
  },
  tinOre: {
    name: "Tin Ore",
    description: "A piece of tin ore.",
    defName: "tinOre",
    price: 0.7,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    itemType: "rawMaterial",
    rarity: "common",
    requiredSkill: undefined,
  },
  ironOre: {
    name: "Iron Ore",
    description: "A piece of iron ore.",
    defName: "ironOre",
    price: 1,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    itemType: "rawMaterial",
    rarity: "common",
    requiredSkill: undefined,
  },
  silverOre: {
    name: "Silver Ore",
    description: "A piece of silver ore.",
    defName: "silverOre",
    price: 2,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    itemType: "rawMaterial",
    rarity: "common",
    requiredSkill: undefined,
  },
  goldOre: {
    name: "Gold Ore",
    description: "A piece of gold ore.",
    defName: "goldOre",
    price: 5,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    itemType: "rawMaterial",
    rarity: "common",
    requiredSkill: undefined,
  },
  titaniumOre: {
    name: "Titanium Ore",
    description: "A piece of titanium ore.",
    defName: "titaniumOre",
    price: 8,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    itemType: "rawMaterial",
    rarity: "common",
    requiredSkill: undefined,
  },
  platinumOre: {
    name: "Platinum Ore",
    description: "A piece of platinum ore.",
    defName: "platinumOre",
    price: 10,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    itemType: "rawMaterial",
    rarity: "common",
    requiredSkill: undefined,
  },
  obsidianOre: {
    name: "Obsidian Ore",
    description: "A piece of obsidian ore.",
    defName: "obsidianOre",
    price: 15,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    itemType: "rawMaterial",
    rarity: "common",
    requiredSkill: undefined,
  },
  tungstenOre: {
    name: "Tungsten Ore",
    description: "A piece of tungsten ore.",
    defName: "tungstenOre",
    price: 20,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    itemType: "rawMaterial",
    rarity: "common",
    requiredSkill: undefined,
  },
  diamondOre: {
    name: "Diamond Ore",
    description: "A piece of diamond ore.",
    defName: "diamondOre",
    price: 50,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    itemType: "rawMaterial",
    rarity: "common",
    requiredSkill: undefined,
  },
  wolframOre: {
    name: "Wolfram Ore",
    description: "A piece of wolfram ore.",
    defName: "wolframOre",
    price: 100,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: false,
    isEquipable: false,
    isEquipped: false,
    equipSlot: undefined,
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 0,
      current: 0,
    },
    isLocked: false,
    requiredLevel: 0,
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
    itemType: "rawMaterial",
    rarity: "common",
    requiredSkill: undefined,
  },
};

export default rawMaterialDefList;
