import Item from "./models/item.type";

const toolWoodcutterAxeDefList: {
  [key: string]: Item;
} = {
  woodcuttersAxe: {
    name: "Woodcutter's Axe",
    description: "An axe for chopping wood.",
    defName: "woodcuttersAxe",
    price: 10,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: true,
    isEquipable: true,
    isEquipped: false,
    equipSlot: "hand",
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 30,
      current: 30,
    },
    isLocked: false,
    requiredLevel: 0,
    requiredSkill: "Woodcutting",
    rarity: "common",
    itemType: "tool",
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
  },
  woodcuttersAxeUncommon: {
    name: "Woodcutter's Axe",
    description: "An uncommon axe for %20 faster chopping wood.",
    defName: "woodcuttersAxeUncommon",
    price: 25,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: true,
    isEquipable: true,
    isEquipped: false,
    equipSlot: "hand",
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 40,
      current: 40,
    },
    isLocked: false,
    requiredLevel: 10,
    requiredSkill: "Woodcutting",
    rarity: "uncommon",
    itemType: "tool",
    bonuses: {
      countdownTime: 2,
      itemAmount: 0,
      itemChance: 0,
    },
  },
  woodcuttersAxeRare: {
    name: "Woodcutter's Axe",
    description: "A rare axe for %30 faster chopping wood.",
    defName: "woodcuttersAxeRare",
    price: 75,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: true,
    isEquipable: true,
    isEquipped: false,
    equipSlot: "hand",
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 50,
      current: 50,
    },
    isLocked: false,
    requiredLevel: 20,
    requiredSkill: "Woodcutting",
    rarity: "rare",
    itemType: "tool",
    bonuses: {
      countdownTime: 3,
      itemAmount: 0,
      itemChance: 0,
    },
  },
  woodcuttersAxeEpic: {
    name: "Woodcutter's Axe",
    description: "An epic axe for %40 faster chopping wood.",
    defName: "woodcuttersAxeEpic",
    price: 150,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: true,
    isEquipable: true,
    isEquipped: false,
    equipSlot: "hand",
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 60,
      current: 60,
    },
    isLocked: false,
    requiredLevel: 30,
    requiredSkill: "Woodcutting",
    rarity: "epic",
    itemType: "tool",
    bonuses: {
      countdownTime: 4,
      itemAmount: 0,
      itemChance: 0,
    },
  },
  woodcuttersAxeLegendary: {
    name: "Woodcutter's Axe",
    description: "An legendary axe for %50 faster chopping wood.",
    defName: "woodcuttersAxeLegendary",
    price: 300,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: true,
    isEquipable: true,
    isEquipped: false,
    equipSlot: "hand",
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 70,
      current: 70,
    },
    isLocked: false,
    requiredLevel: 50,
    requiredSkill: "Woodcutting",
    rarity: "legendary",
    itemType: "tool",
    bonuses: {
      countdownTime: 5,
      itemAmount: 0,
      itemChance: 0,
    },
  },
};

export default toolWoodcutterAxeDefList;
