import Item from "./models/item.type";

const toolPickaxeDefList: {
  [key: string]: Item;
} = {
  pickaxe: {
    name: "Pickaxe",
    description: "A pickaxe for mining.",
    defName: "pickaxe",
    price: 10,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: true,
    isEquipable: true,
    isEquipped: false,
    equipSlot: "hand",
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 30,
      current: 30,
    },
    isLocked: false,
    requiredLevel: 0,
    requiredSkill: "Mining",
    rarity: "common",
    itemType: "tool",
    bonuses: {
      countdownTime: 0,
      itemAmount: 0,
      itemChance: 0,
    },
  },
  pickaxeUncommon: {
    name: "Pickaxe",
    description: "An uncommon pickaxe for %20 faster mining.",
    defName: "pickaxeUncommon",
    price: 25,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: true,
    isEquipable: true,
    isEquipped: false,
    equipSlot: "hand",
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 40,
      current: 40,
    },
    isLocked: false,
    requiredLevel: 10,
    requiredSkill: "Mining",
    rarity: "uncommon",
    itemType: "tool",
    bonuses: {
      countdownTime: 2,
      itemAmount: 0,
      itemChance: 0,
    },
  },
  pickaxeRare: {
    name: "Pickaxe",
    description: "A rare pickaxe for %30 faster mining.",
    defName: "pickaxeRare",
    price: 75,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: true,
    isEquipable: true,
    isEquipped: false,
    equipSlot: "hand",
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 50,
      current: 50,
    },
    isLocked: false,
    requiredLevel: 20,
    requiredSkill: "Mining",
    rarity: "rare",
    itemType: "tool",
    bonuses: {
      countdownTime: 3,
      itemAmount: 0,
      itemChance: 0,
    },
  },
  pickaxeEpic: {
    name: "Pickaxe",
    description: "An epic pickaxe for %40 faster mining.",
    defName: "pickaxeEpic",
    price: 150,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: true,
    isEquipable: true,
    isEquipped: false,
    equipSlot: "hand",
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 60,
      current: 60,
    },
    isLocked: false,
    requiredLevel: 30,
    requiredSkill: "Mining",
    rarity: "epic",
    itemType: "tool",
    bonuses: {
      countdownTime: 4,
      itemAmount: 0,
      itemChance: 0,
    },
  },
  pickaxeLegendary: {
    name: "Pickaxe",
    description: "An legendary pickaxe for %50 faster mining.",
    defName: "pickaxeLegendary",
    price: 300,
    isCookable: false,
    processedItem: undefined,
    isEdible: false,
    isSalable: true,
    isBuyable: true,
    isEquipable: true,
    isEquipped: false,
    equipSlot: "hand",
    amount: 0,
    hungerRestore: 0,
    hp: {
      max: 70,
      current: 70,
    },
    isLocked: false,
    requiredLevel: 50,
    requiredSkill: "Mining",
    rarity: "legendary",
    itemType: "tool",
    bonuses: {
      countdownTime: 5,
      itemAmount: 0,
      itemChance: 0,
    },
  },
};

export default toolPickaxeDefList;
